{"name":"MongoNetworkError","errorLabels":["TransientTransactionError"],"level":"error","message":"Error connecting to database: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]","stack":"MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (/Users/sechikson/Documents/NodeJS/winnow-pallindrome/api/node_modules/mongodb/lib/core/topologies/server.js:431:11)\n    at emitOne (events.js:116:13)\n    at Pool.emit (events.js:211:7)\n    at connect (/Users/sechikson/Documents/NodeJS/winnow-pallindrome/api/node_modules/mongodb/lib/core/connection/pool.js:580:14)\n    at makeConnection (/Users/sechikson/Documents/NodeJS/winnow-pallindrome/api/node_modules/mongodb/lib/core/connection/connect.js:39:11)\n    at callback (/Users/sechikson/Documents/NodeJS/winnow-pallindrome/api/node_modules/mongodb/lib/core/connection/connect.js:261:5)\n    at Socket.err (/Users/sechikson/Documents/NodeJS/winnow-pallindrome/api/node_modules/mongodb/lib/core/connection/connect.js:286:7)\n    at Object.onceWrapper (events.js:315:30)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","timestamp":"2019-09-14T01:05:38.211Z"}
